import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import TheHeader from './components/TheHeader'
import TheFooter from './components/TheFooter'

import { Unbounded } from 'next/font/google'
const font = Unbounded({
    weight: '400',
    subsets: ['latin'],
    display: 'swap',
  })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className='flex flex-col items-center justify-between  h-[100vh]'>
        <div className='w-full'>
        <TheHeader />
          {children}
        </div>
        <TheFooter />
        </div>
      

      </body>
    </html>
  );
}
